version: '2'
services:
  db:
    image: mysql:5.7.4
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_DATABASE=peekpa_db1
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Peekpa2020
      - MYSQL_PASSWORD=Peekpa2020

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
